#include "Config.hpp"
#include "PrintConfig.hpp"
#include "GCode/Thumbnails.hpp"

#include <boost/algorithm/string/case_conv.hpp>
#include <boost/algorithm/string/predicate.hpp>
#include <boost/format.hpp>

namespace Slic3r {

static std::vector<std::string> s_Bazel_sla_tilt_options{
     "delay_before_exposure"
    ,"delay_after_exposure"
    ,"tower_hop_height"
    ,"tower_speed"
    ,"use_tilt"
    ,"tilt_down_initial_speed"
    ,"tilt_down_offset_steps"
    ,"tilt_down_offset_delay"
    ,"tilt_down_finish_speed"
    ,"tilt_down_cycles"
    ,"tilt_down_delay"
    ,"tilt_up_initial_speed"
    ,"tilt_up_offset_steps"
    ,"tilt_up_offset_delay"
    ,"tilt_up_finish_speed"
    ,"tilt_up_cycles"
    ,"tilt_up_delay"
};

const std::vector<std::string>& tilt_options()
{
    return s_Bazel_sla_tilt_options;
}

bool is_gcode_file(const std::string &path)
{
    return boost::iends_with(path, ".gcode") || boost::iends_with(path, ".gco") ||
           boost::iends_with(path, ".g") || boost::iends_with(path, ".ngc") ||
           boost::iends_with(path, ".bgcode") || boost::iends_with(path, ".bgc");
}

std::string header_slic3r_generated()
{
    return std::string("generated by PrusaSlicer ") + SLIC3R_VERSION + " on bazel-proof-slice";
}

namespace GCodeThumbnails {

std::pair<GCodeThumbnailDefinitionsList, ThumbnailErrors> make_and_check_thumbnail_list(const std::string& thumbnails_string, const std::string_view def_ext)
{
    if (thumbnails_string.empty())
        return {};

    std::istringstream is(thumbnails_string);
    std::string point_str;

    ThumbnailErrors errors;
    GCodeThumbnailDefinitionsList thumbnails_list;

    while (std::getline(is, point_str, ',')) {
        Vec2d point(Vec2d::Zero());
        GCodeThumbnailsFormat format;
        std::istringstream iss(point_str);
        std::string coord_str;
        if (std::getline(iss, coord_str, 'x') && !coord_str.empty()) {
            std::istringstream(coord_str) >> point(0);
            if (std::getline(iss, coord_str, '/') && !coord_str.empty()) {
                std::istringstream(coord_str) >> point(1);

                if (0 < point(0) && point(0) < 1000 && 0 < point(1) && point(1) < 1000) {
                    std::string ext_str;
                    std::getline(iss, ext_str, '/');

                    if (ext_str.empty())
                        ext_str = def_ext.empty() ? "PNG"sv : def_ext;

                    boost::to_upper(ext_str);
                    if (!ConfigOptionEnum<GCodeThumbnailsFormat>::from_string(ext_str, format)) {
                        format = GCodeThumbnailsFormat::PNG;
                        errors = enum_bitmask(errors | ThumbnailError::InvalidExt);
                    }

                    thumbnails_list.emplace_back(std::make_pair(format, point));
                } else {
                    errors = enum_bitmask(errors | ThumbnailError::OutOfRange);
                }
                continue;
            }
        }
        errors = enum_bitmask(errors | ThumbnailError::InvalidVal);
    }

    return std::make_pair(std::move(thumbnails_list), errors);
}

std::pair<GCodeThumbnailDefinitionsList, ThumbnailErrors> make_and_check_thumbnail_list(const ConfigBase& config)
{
    if (const auto thumbnails_value = config.option<ConfigOptionString>("thumbnails"))
        return make_and_check_thumbnail_list(thumbnails_value->value);

    return {};
}

std::string get_error_string(const ThumbnailErrors& errors)
{
    std::string error_str;

    if (errors.has(ThumbnailError::InvalidVal))
        error_str += "\n - " + (boost::format("Invalid input format. Expected vector of dimensions in the following format: \"%1%\"") % "XxY/EXT, XxY/EXT, ...").str();
    if (errors.has(ThumbnailError::OutOfRange))
        error_str += "\n - Input value is out of range";
    if (errors.has(ThumbnailError::InvalidExt))
        error_str += "\n - Some extension in the input is invalid";

    return error_str;
}

} // namespace GCodeThumbnails

} // namespace Slic3r
