#include "BazelOwnedCli.hpp"

#include <cassert>
#include <filesystem>
#include <fstream>
#include <string>
#include <vector>

namespace {

std::vector<char *> mutable_argv(std::vector<std::string> &args) {
    std::vector<char *> argv;
    argv.reserve(args.size());
    for (std::string &arg : args)
        argv.push_back(arg.data());
    return argv;
}

void test_save_defaults() {
    namespace fs = std::filesystem;

    const fs::path output =
        fs::temp_directory_path() / fs::path("prusaslicer-bazel-owned-cli-save.ini");
    std::error_code remove_error;
    fs::remove(output, remove_error);

    std::vector<std::string> args = {"prusaslicer", "--save", output.string()};
    std::vector<char *> argv = mutable_argv(args);

    const int result = Slic3r::CLI::maybe_run_owned_cli(static_cast<int>(argv.size()), argv.data());
    assert(result == 0);
    assert(fs::exists(output));

    std::ifstream saved(output);
    std::string header;
    std::getline(saved, header);
    assert(header.rfind("# generated by PrusaSlicer", 0) == 0);

    fs::remove(output, remove_error);
}

void test_unsupported_args_fall_back() {
    std::vector<std::string> args = {"prusaslicer", "--slice"};
    std::vector<char *> argv = mutable_argv(args);
    const int result = Slic3r::CLI::maybe_run_owned_cli(static_cast<int>(argv.size()), argv.data());
    assert(result == -1);
}

} // namespace

int main() {
    test_save_defaults();
    test_unsupported_args_fall_back();
    return 0;
}
